### ISSUE TITLE
[리뷰 반영] 즐겨찾기 관련 리뷰 반영

### ISSUE THREAD

**Issue by Modyhoon** [boostcampwm-2021/iOS09-BBus#197]
## 작업 내용
- [x] thread -> queue 용어 수정 (#93)
- [x] homeUsecase 내에 사용하는 Usecase typealias로 분리 (#98)
- [x] home HeaderView에 headerViewTapped함수 위치 변경 (#98)
- [x] HomeUsecase 프로퍼티에 private(set) 추가 (#101)
- [x] 튜플에 파라미터 이름을 주어 .0, .1로 접근하는 것이 아닌 파라미터 이름으로 접근하도록 수정 (#156)
- [x] HomeModel 클로저 내 파라미터 네이밍 수정 (#156)
- [x] row -> item 으로 수정 및 HomeFavorite typealias 설정 (#156)
- [x] convention 에 의해 파라미터 개행 (#156)

## 레퍼런스
없음.
